[tool.poetry]
name = "magisterka"
version = "0.1.0"
description = ""
authors = ["chwilko <bartekchwilkowski@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
black = {extras = ["jupyter"], version = "^23.3.0"}
isort = "^5.12.0"
pylint = "^2.17.2"
mypy = "^1.2.0"
pandas = "^2.0.0"
matplotlib = "^3.7.1"
seaborn = "^0.12.2"
ipykernel = "^6.22.0"
PyQt5 = "5.9.2"
beautifulsoup4 = "^4.12.2"
alive-progress = "^3.1.1"
certifi = "^2022.12.7"
requests = "^2.29.0"
gdshortener = "^1.0.1"
ipdb = "^0.13.13"
tqdm = "^4.65.0"
statsmodels = "^0.14.0"
multiprocess = "^0.70.14"
convert-jupyter = "^0.1.10"
pytest = "^7.3.1"
hypothesis = "^6.76.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
