from .constants import CV as CV, EV as EV, PHEV as PHEV
from _typeshed import Incomplete

class Car:
    release_year: Incomplete
    def __init__(self, release_year) -> None: ...
    def is_operational(self, year: int) -> bool: ...
    @property
    def lifetime(self) -> None: ...
    @property
    def car_type(self) -> None: ...

class Car_EV(Car):
    @property
    def lifetime(self): ...
    @property
    def car_type(self): ...

class Car_CV(Car):
    @property
    def lifetime(self): ...
    @property
    def car_type(self): ...

class Car_PHEV(Car):
    @property
    def lifetime(self): ...
    @property
    def car_type(self): ...
