from _typeshed import Incomplete
from interface.model.Custormer import Customer as Customer
from typing import Tuple

class City:
    charger_pos: Incomplete
    city_size: Incomplete
    def __init__(self, city_size: Tuple[int, int], initial_chargers: int) -> None: ...
    def is_nerby(self, customer: Customer, radius: float): ...
    def build_new(self, new_chargers: int): ...
    def count_chargers(self): ...
