from typing import Tuple

from _typeshed import Incomplete

class City:
    charger_pos: Incomplete
    city_size: Incomplete
    def __init__(self, city_size: Tuple[int, int], initial_chargers: int) -> None: ...
    def is_nerby(self, customer, radius: float): ...
    def build_new(self, new_chargers: int): ...
    def count_chargers(self): ...
