from .Cars import Car as Car, Car_CV as Car_CV, Car_EV as Car_EV, Car_PHEV as Car_PHEV
from .constants import CV as CV, EV as EV, PHEV as PHEV
from _typeshed import Incomplete
from typing import Tuple

class Customer:
    car: Incomplete
    profile: Incomplete
    def __init__(self, car: Car, profile: int, city_size: Tuple[float, float]) -> None: ...
    def have_working_car(self, year: int) -> bool: ...
    def get_car_type(self) -> str: ...
    def buy(self, car_type: str, current_year: int): ...
    def choose(self, car_type1, car_type2, current_year) -> None: ...
    @property
    def home(self): ...
