from _typeshed import Incomplete

class Goverment:
    society: Incomplete
    def __init__(self, society) -> None: ...
    def get_subsidy(self) -> int: ...
    def get_subsidy_val(self) -> int: ...
    def update(self) -> None: ...
